<MenuScreen>:
    canvas.before:
        Color:
            rgba: rgba("#B01825")
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation: "vertical"
        padding: "20dp"
        spacing: "20dp"
        Label:
            id: title_game
            text: "Dyploma clicker"
            font_name: "assets/Graduate-Regular.ttf"
            color: "#331109"
            font_size: "40sp"
            font_weigth: 800